# Clump finder config: n5120 snapshot 35, connectivity 6, T < 0.02

dataset_path: /lustre/orion/ast207/proj-shared/mpturb/clumpn5120/parthenon.opmd.00035.bp/
step: 35
output_dir: ./clump_out/n5120_step35/conn6_T0p02
log_dir: ./logs/n5120_step35/conn6_T0p02

temperature_threshold: 0.02
connectivity: 6
min_clump_cells: 8

Nres: 5120
dx: null
dy: null
dz: null
origin: [0.0, 0.0, 0.0]
periodic: [true, true, true]
assert_nres_from_data: true

intra_node_threads: 56
mpi_mode: "one_rank_per_node"
verify_one_rank_per_node: true

tile_shape: [1280, 1280, 1280]

field_dtype: float32
accum_dtype: float64

save_pressure: false
save_per_clump_voxel_bbox: true

ghost_width: 1
stitch_flag: false

gamma: 1.6666666666666667
profile: false
