# Example configuration for clump_finder

# Input/output
dataset_path: /lustre/orion/ast207/proj-shared/mpturb/clumpn640/parthenon.opmd.00035.bp/
step: 35
output_dir: ./clump_out/clumpn640_step35
log_dir: ./logs

# Selection (code units)
temperature_threshold: 0.1
connectivity: 6                        # 6 only (18/26 disabled)
min_clump_cells: 27                    # ignore clumps smaller than this cell count

# Geometry (cubic grid)
Nres: 640
dx: null
dy: null
dz: null
origin: [0.0, 0.0, 0.0]
periodic: [true, true, true]
assert_nres_from_data: true

# Parallelism
intra_node_threads: 56
mpi_mode: "one_rank_per_node"
verify_one_rank_per_node: true

# Tiling inside a node (not the MPI split)
tile_shape: [640, 640, 640]

# Memory / precision
field_dtype: float32
accum_dtype: float64

# Output content
save_pressure: false
save_per_clump_voxel_bbox: true

# Ghost zones (0 or 1): include ghost cells from neighboring domain regions; wrap at global domain edges only
ghost_width: 1
stitch_flag: false

# Misc
gamma: 1.6666666666666667
profile: false
